# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9d6c983f21316e467b64ab46b336b0f55ebcbf2fd83e0f12ea7551f4cc1b855a711552f20b904b96ef1ec758be2c7f2103acbdaddc09220410ff54f235c078f

test:
  secret_key_base: 16e4a542ef192424efa5f8a7a4e441fdf159bf3f48904ea4a758c9c66ffbfc018556970ff57d1e790c0d7438fbf2144395d43a56b6ac92da13e91efcf8cc5237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
